# Apex Realty AI – California Housing Price Prediction


## Project Objective

The objective of this project is to predict residential housing market prices using the California Housing dataset.

### Target
Median House Value

### Primary Evaluation Metrics
- RMSE
- MAE
- R²
- Residual Analysis

### Role
Data Engineer – Member 1

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries imported successfully!")

Libraries imported successfully!


In [1]:
from pathlib import Path
import pandas as pd
from sklearn.datasets import fetch_california_housing

print("Libraries imported successfully!")

Libraries imported successfully!


In [2]:
# Create the raw data folder
raw_dir = Path("../data/raw")
raw_dir.mkdir(parents=True, exist_ok=True)

print("Raw data folder is ready!")

Raw data folder is ready!


In [3]:
# Download and load California Housing dataset
housing = fetch_california_housing(as_frame=True)

# Convert dataset into a DataFrame
df = housing.frame

print("Dataset downloaded and loaded successfully!")
print("Dataset shape:", df.shape)

Dataset downloaded and loaded successfully!
Dataset shape: (20640, 9)


In [4]:
# Save the original dataset without modifying it
raw_file = raw_dir / "california_housing.csv"

df.to_csv(raw_file, index=False)

print("Raw dataset saved successfully!")
print("File location:", raw_file)

Raw dataset saved successfully!
File location: ..\data\raw\california_housing.csv


In [5]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("\nColumn names:")
print(df.columns.tolist())

Rows: 20640
Columns: 9

Column names:
['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude', 'MedHouseVal']


In [6]:
from pathlib import Path
import pandas as pd

raw_file = Path("../data/raw/california_housing.csv")

df = pd.read_csv(raw_file)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (20640, 9)


In [7]:
print("Column names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

Column names:
['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude', 'MedHouseVal']

Data types:
MedInc         float64
HouseAge       float64
AveRooms       float64
AveBedrms      float64
Population     float64
AveOccup       float64
Latitude       float64
Longitude      float64
MedHouseVal    float64
dtype: object


In [8]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64


In [9]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0


In [10]:
print("Statistical Summary:")
print(df.describe())

Statistical Summary:
             MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude   MedHouseVal  
count  20640.000000  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704      2.068558  
std       10.386050      2.135952      2.003532      1.153956  
min        

In [11]:
print("Minimum value of each column:")
print(df.min())

Minimum value of each column:
MedInc           0.499900
HouseAge         1.000000
AveRooms         0.846154
AveBedrms        0.333333
Population       3.000000
AveOccup         0.692308
Latitude        32.540000
Longitude     -124.350000
MedHouseVal      0.149990
dtype: float64


In [12]:
print("Maximum value of each column:")
print(df.max())

Maximum value of each column:
MedInc            15.000100
HouseAge          52.000000
AveRooms         141.909091
AveBedrms         34.066667
Population     35682.000000
AveOccup        1243.333333
Latitude          41.950000
Longitude       -114.310000
MedHouseVal        5.000010
dtype: float64


In [13]:
print("Invalid value checks:")

print("Negative MedInc:", (df["MedInc"] < 0).sum())
print("Invalid HouseAge:", (df["HouseAge"] <= 0).sum())
print("Invalid Population:", (df["Population"] <= 0).sum())
print("Invalid AveOccup:", (df["AveOccup"] <= 0).sum())

Invalid value checks:
Negative MedInc: 0
Invalid HouseAge: 0
Invalid Population: 0
Invalid AveOccup: 0


In [14]:
print("Invalid Latitude:", ((df["Latitude"] < -90) | (df["Latitude"] > 90)).sum())
print("Invalid Longitude:", ((df["Longitude"] < -180) | (df["Longitude"] > 180)).sum())

Invalid Latitude: 0
Invalid Longitude: 0


In [15]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_counts = ((df < lower_bound) | (df > upper_bound)).sum()

print("Potential outliers using IQR:")
print(outlier_counts)

Potential outliers using IQR:
MedInc          681
HouseAge          0
AveRooms        511
AveBedrms      1424
Population     1196
AveOccup        711
Latitude          0
Longitude         0
MedHouseVal    1071
dtype: int64


In [16]:
print("Top 5 highest values:")

for column in df.columns:
    print(f"\n{column}:")
    print(df[column].nlargest(5).values)

Top 5 highest values:

MedInc:
[15.0001 15.0001 15.0001 15.0001 15.0001]

HouseAge:
[52. 52. 52. 52. 52.]

AveRooms:
[141.90909091 132.53333333  62.42222222  61.8125      59.875     ]

AveBedrms:
[34.06666667 25.63636364 15.3125     14.11111111 11.41071429]

Population:
[35682. 28566. 16305. 16122. 15507.]

AveOccup:
[1243.33333333  599.71428571  502.46153846  230.17241379   83.17142857]

Latitude:
[41.95 41.95 41.92 41.88 41.86]

Longitude:
[-114.31 -114.47 -114.49 -114.55 -114.56]

MedHouseVal:
[5.00001 5.00001 5.00001 5.00001 5.00001]


In [17]:
outlier_summary = pd.DataFrame({
    "Column": outlier_counts.index,
    "Potential_Outliers_IQR": outlier_counts.values
})

print(outlier_summary)

        Column  Potential_Outliers_IQR
0       MedInc                     681
1     HouseAge                       0
2     AveRooms                     511
3    AveBedrms                    1424
4   Population                    1196
5     AveOccup                     711
6     Latitude                       0
7    Longitude                       0
8  MedHouseVal                    1071


In [18]:
clean_df = df.copy()

print("Cleaned dataset shape:", clean_df.shape)
print("Missing values:", clean_df.isnull().sum().sum())
print("Duplicate rows:", clean_df.duplicated().sum())

Cleaned dataset shape: (20640, 9)
Missing values: 0
Duplicate rows: 0


In [19]:
from pathlib import Path

processed_folder = Path("../data/processed")
processed_folder.mkdir(parents=True, exist_ok=True)

clean_file = processed_folder / "cleaned_california_housing.csv"

clean_df.to_csv(clean_file, index=False)

print("Cleaned dataset saved successfully!")
print("File:", clean_file)

Cleaned dataset saved successfully!
File: ..\data\processed\cleaned_california_housing.csv


In [20]:
# Separate features and target

X = clean_df.drop("MedHouseVal", axis=1)
y = clean_df["MedHouseVal"]

print("Features (X):")
print(X.columns.tolist())

print("\nTarget (y):")
print(y.name)

print("\nFeature shape:", X.shape)
print("Target shape:", y.shape)

Features (X):
['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

Target (y):
MedHouseVal

Feature shape: (20640, 8)
Target shape: (20640,)


In [21]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)
print("Training target shape:", y_train.shape)
print("Testing target shape:", y_test.shape)

Training data shape: (16512, 8)
Testing data shape: (4128, 8)
Training target shape: (16512,)
Testing target shape: (4128,)


In [22]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Create preprocessing pipeline
preprocessor = Pipeline([
    ("scaler", StandardScaler())
])

print("Preprocessing pipeline created successfully!")
print(preprocessor)

Preprocessing pipeline created successfully!
Pipeline(steps=[('scaler', StandardScaler())])


In [23]:
# Fit the preprocessing pipeline only on training data
X_train_processed = preprocessor.fit_transform(X_train)

# Use the same fitted pipeline to transform test data
X_test_processed = preprocessor.transform(X_test)

print("Training data after preprocessing:", X_train_processed.shape)
print("Testing data after preprocessing:", X_test_processed.shape)

Training data after preprocessing: (16512, 8)
Testing data after preprocessing: (4128, 8)


In [24]:
from pathlib import Path

processed_folder = Path("../data/processed")
processed_folder.mkdir(parents=True, exist_ok=True)

# Convert processed arrays into DataFrames
X_train_processed_df = pd.DataFrame(
    X_train_processed,
    columns=X.columns
)

X_test_processed_df = pd.DataFrame(
    X_test_processed,
    columns=X.columns
)

# Add target column
X_train_processed_df["MedHouseVal"] = y_train.values
X_test_processed_df["MedHouseVal"] = y_test.values

# Save processed datasets
X_train_processed_df.to_csv(
    processed_folder / "train_processed.csv",
    index=False
)

X_test_processed_df.to_csv(
    processed_folder / "test_processed.csv",
    index=False
)

print("Processed training and testing datasets saved successfully!")
print("Training file:", processed_folder / "train_processed.csv")
print("Testing file:", processed_folder / "test_processed.csv")

Processed training and testing datasets saved successfully!
Training file: ..\data\processed\train_processed.csv
Testing file: ..\data\processed\test_processed.csv


In [25]:
# Create data quality audit log

audit_log = pd.DataFrame({
    "Check": [
        "Dataset Shape",
        "Missing Values",
        "Duplicate Rows",
        "Invalid MedInc",
        "Invalid HouseAge",
        "Invalid Population",
        "Invalid AveOccup",
        "Invalid Latitude",
        "Invalid Longitude",
        "Potential Outliers"
    ],
    "Result": [
        str(df.shape),
        int(df.isnull().sum().sum()),
        int(df.duplicated().sum()),
        int((df["MedInc"] < 0).sum()),
        int((df["HouseAge"] <= 0).sum()),
        int((df["Population"] <= 0).sum()),
        int((df["AveOccup"] <= 0).sum()),
        int(((df["Latitude"] < -90) | (df["Latitude"] > 90)).sum()),
        int(((df["Longitude"] < -180) | (df["Longitude"] > 180)).sum()),
        int(outlier_counts.sum())
    ]
})

print(audit_log)

                Check      Result
0       Dataset Shape  (20640, 9)
1      Missing Values           0
2      Duplicate Rows           0
3      Invalid MedInc           0
4    Invalid HouseAge           0
5  Invalid Population           0
6    Invalid AveOccup           0
7    Invalid Latitude           0
8   Invalid Longitude           0
9  Potential Outliers        5594


In [26]:
# Save data quality audit log

audit_file = processed_folder / "data_quality_audit.csv"

audit_log.to_csv(audit_file, index=False)

print("Data quality audit log saved successfully!")
print("File:", audit_file)

Data quality audit log saved successfully!
File: ..\data\processed\data_quality_audit.csv
